[project]
name = "server"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.2.3",
    "fastapi>=0.120.2",
    "fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.14",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.27",
    "uvicorn[standard]>=0.38.0",
]
