name: Continuous Deployment to DigitalOcean

on:
  push:
    tags:
      - "server-v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Transfer files via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: server/docker-compose.yml
          target: ~/zhura-server/
          strip_components: 1
          overwrite: true

      - name: Deploy Containers via SSH
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/zhura-server/
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            docker compose pull

            docker compose up -d --force-recreate

            docker image prune -f
        env:
          DB: ${{ secrets.DB }}
          COMPOSIO_MCP_URL: ${{ secrets.COMPOSIO_MCP_URL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
